services:
  cupsd:
    image: bartekmp/cupsane:latest
    container_name: cupsane
    privileged: true
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/dbus:/var/run/dbus
      - /dev/bus/usb:/dev/bus/usb
      - ./storage/cups-config:/etc/cups
      - ./storage/cups-cache:/var/cache/cups
      - ./storage/cups-spool:/var/spool/cups
      - ./storage/scans:/var/lib/scanservjs/output
    environment:
      - TZ=Europe/Warsaw
      - SANE_FORCE_HPAIO_ONLY=1
